//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glue.SolrRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://test.solr.org/", ConfigurationName="SolrRef.SolrTest")]
    public interface SolrTest {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://test.solr.org/SolrTest/splitrowRequest", ReplyAction="http://test.solr.org/SolrTest/splitrowResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Glue.SolrRef.splitrowResponse splitrow(Glue.SolrRef.splitrowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://test.solr.org/SolrTest/splitrowRequest", ReplyAction="http://test.solr.org/SolrTest/splitrowResponse")]
        System.Threading.Tasks.Task<Glue.SolrRef.splitrowResponse> splitrowAsync(Glue.SolrRef.splitrowRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://test.solr.org/SolrTest/solrqRequest", ReplyAction="http://test.solr.org/SolrTest/solrqResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Glue.SolrRef.solrqResponse solrq(Glue.SolrRef.solrqRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://test.solr.org/SolrTest/solrqRequest", ReplyAction="http://test.solr.org/SolrTest/solrqResponse")]
        System.Threading.Tasks.Task<Glue.SolrRef.solrqResponse> solrqAsync(Glue.SolrRef.solrqRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://test.solr.org/SolrTest/NounVerbRequest", ReplyAction="http://test.solr.org/SolrTest/NounVerbResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Glue.SolrRef.NounVerbResponse NounVerb(Glue.SolrRef.NounVerbRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://test.solr.org/SolrTest/NounVerbRequest", ReplyAction="http://test.solr.org/SolrTest/NounVerbResponse")]
        System.Threading.Tasks.Task<Glue.SolrRef.NounVerbResponse> NounVerbAsync(Glue.SolrRef.NounVerbRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://test.solr.org/SolrTest/spellcheckRequest", ReplyAction="http://test.solr.org/SolrTest/spellcheckResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Glue.SolrRef.spellcheckResponse spellcheck(Glue.SolrRef.spellcheckRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://test.solr.org/SolrTest/spellcheckRequest", ReplyAction="http://test.solr.org/SolrTest/spellcheckResponse")]
        System.Threading.Tasks.Task<Glue.SolrRef.spellcheckResponse> spellcheckAsync(Glue.SolrRef.spellcheckRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://test.solr.org/SolrTest/QueryRetRequest", ReplyAction="http://test.solr.org/SolrTest/QueryRetResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Glue.SolrRef.QueryRetResponse QueryRet(Glue.SolrRef.QueryRetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://test.solr.org/SolrTest/QueryRetRequest", ReplyAction="http://test.solr.org/SolrTest/QueryRetResponse")]
        System.Threading.Tasks.Task<Glue.SolrRef.QueryRetResponse> QueryRetAsync(Glue.SolrRef.QueryRetRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://test.solr.org/SolrTest/AutoCompleteRequest", ReplyAction="http://test.solr.org/SolrTest/AutoCompleteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Glue.SolrRef.AutoCompleteResponse AutoComplete(Glue.SolrRef.AutoCompleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://test.solr.org/SolrTest/AutoCompleteRequest", ReplyAction="http://test.solr.org/SolrTest/AutoCompleteResponse")]
        System.Threading.Tasks.Task<Glue.SolrRef.AutoCompleteResponse> AutoCompleteAsync(Glue.SolrRef.AutoCompleteRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://test.solr.org/SolrTest/AutoSugRequest", ReplyAction="http://test.solr.org/SolrTest/AutoSugResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Glue.SolrRef.AutoSugResponse AutoSug(Glue.SolrRef.AutoSugRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://test.solr.org/SolrTest/AutoSugRequest", ReplyAction="http://test.solr.org/SolrTest/AutoSugResponse")]
        System.Threading.Tasks.Task<Glue.SolrRef.AutoSugResponse> AutoSugAsync(Glue.SolrRef.AutoSugRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://test.solr.org/SolrTest/splitterRequest", ReplyAction="http://test.solr.org/SolrTest/splitterResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Glue.SolrRef.splitterResponse splitter(Glue.SolrRef.splitterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://test.solr.org/SolrTest/splitterRequest", ReplyAction="http://test.solr.org/SolrTest/splitterResponse")]
        System.Threading.Tasks.Task<Glue.SolrRef.splitterResponse> splitterAsync(Glue.SolrRef.splitterRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="splitrow", WrapperNamespace="http://test.solr.org/", IsWrapped=true)]
    public partial class splitrowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://test.solr.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string q;
        
        public splitrowRequest() {
        }
        
        public splitrowRequest(string q) {
            this.q = q;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="splitrowResponse", WrapperNamespace="http://test.solr.org/", IsWrapped=true)]
    public partial class splitrowResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://test.solr.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] @return;
        
        public splitrowResponse() {
        }
        
        public splitrowResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solrq", WrapperNamespace="http://test.solr.org/", IsWrapped=true)]
    public partial class solrqRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://test.solr.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string q1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://test.solr.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string q2;
        
        public solrqRequest() {
        }
        
        public solrqRequest(string q1, string q2) {
            this.q1 = q1;
            this.q2 = q2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solrqResponse", WrapperNamespace="http://test.solr.org/", IsWrapped=true)]
    public partial class solrqResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://test.solr.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public solrqResponse() {
        }
        
        public solrqResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NounVerb", WrapperNamespace="http://test.solr.org/", IsWrapped=true)]
    public partial class NounVerbRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://test.solr.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string query;
        
        public NounVerbRequest() {
        }
        
        public NounVerbRequest(string query) {
            this.query = query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NounVerbResponse", WrapperNamespace="http://test.solr.org/", IsWrapped=true)]
    public partial class NounVerbResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://test.solr.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] @return;
        
        public NounVerbResponse() {
        }
        
        public NounVerbResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="spellcheck", WrapperNamespace="http://test.solr.org/", IsWrapped=true)]
    public partial class spellcheckRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://test.solr.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string key;
        
        public spellcheckRequest() {
        }
        
        public spellcheckRequest(string key) {
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="spellcheckResponse", WrapperNamespace="http://test.solr.org/", IsWrapped=true)]
    public partial class spellcheckResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://test.solr.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public spellcheckResponse() {
        }
        
        public spellcheckResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryRet", WrapperNamespace="http://test.solr.org/", IsWrapped=true)]
    public partial class QueryRetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://test.solr.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://test.solr.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string field;
        
        public QueryRetRequest() {
        }
        
        public QueryRetRequest(string key, string field) {
            this.key = key;
            this.field = field;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryRetResponse", WrapperNamespace="http://test.solr.org/", IsWrapped=true)]
    public partial class QueryRetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://test.solr.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] @return;
        
        public QueryRetResponse() {
        }
        
        public QueryRetResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AutoComplete", WrapperNamespace="http://test.solr.org/", IsWrapped=true)]
    public partial class AutoCompleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://test.solr.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string q;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://test.solr.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int limit;
        
        public AutoCompleteRequest() {
        }
        
        public AutoCompleteRequest(string q, int limit) {
            this.q = q;
            this.limit = limit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AutoCompleteResponse", WrapperNamespace="http://test.solr.org/", IsWrapped=true)]
    public partial class AutoCompleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://test.solr.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] @return;
        
        public AutoCompleteResponse() {
        }
        
        public AutoCompleteResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AutoSug", WrapperNamespace="http://test.solr.org/", IsWrapped=true)]
    public partial class AutoSugRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://test.solr.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string q;
        
        public AutoSugRequest() {
        }
        
        public AutoSugRequest(string q) {
            this.q = q;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AutoSugResponse", WrapperNamespace="http://test.solr.org/", IsWrapped=true)]
    public partial class AutoSugResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://test.solr.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] @return;
        
        public AutoSugResponse() {
        }
        
        public AutoSugResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="splitter", WrapperNamespace="http://test.solr.org/", IsWrapped=true)]
    public partial class splitterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://test.solr.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string info;
        
        public splitterRequest() {
        }
        
        public splitterRequest(string info) {
            this.info = info;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="splitterResponse", WrapperNamespace="http://test.solr.org/", IsWrapped=true)]
    public partial class splitterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://test.solr.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] @return;
        
        public splitterResponse() {
        }
        
        public splitterResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SolrTestChannel : Glue.SolrRef.SolrTest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SolrTestClient : System.ServiceModel.ClientBase<Glue.SolrRef.SolrTest>, Glue.SolrRef.SolrTest {
        
        public SolrTestClient() {
        }
        
        public SolrTestClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SolrTestClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SolrTestClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SolrTestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Glue.SolrRef.splitrowResponse Glue.SolrRef.SolrTest.splitrow(Glue.SolrRef.splitrowRequest request) {
            return base.Channel.splitrow(request);
        }
        
        public string[] splitrow(string q) {
            Glue.SolrRef.splitrowRequest inValue = new Glue.SolrRef.splitrowRequest();
            inValue.q = q;
            Glue.SolrRef.splitrowResponse retVal = ((Glue.SolrRef.SolrTest)(this)).splitrow(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Glue.SolrRef.splitrowResponse> Glue.SolrRef.SolrTest.splitrowAsync(Glue.SolrRef.splitrowRequest request) {
            return base.Channel.splitrowAsync(request);
        }
        
        public System.Threading.Tasks.Task<Glue.SolrRef.splitrowResponse> splitrowAsync(string q) {
            Glue.SolrRef.splitrowRequest inValue = new Glue.SolrRef.splitrowRequest();
            inValue.q = q;
            return ((Glue.SolrRef.SolrTest)(this)).splitrowAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Glue.SolrRef.solrqResponse Glue.SolrRef.SolrTest.solrq(Glue.SolrRef.solrqRequest request) {
            return base.Channel.solrq(request);
        }
        
        public string solrq(string q1, string q2) {
            Glue.SolrRef.solrqRequest inValue = new Glue.SolrRef.solrqRequest();
            inValue.q1 = q1;
            inValue.q2 = q2;
            Glue.SolrRef.solrqResponse retVal = ((Glue.SolrRef.SolrTest)(this)).solrq(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Glue.SolrRef.solrqResponse> Glue.SolrRef.SolrTest.solrqAsync(Glue.SolrRef.solrqRequest request) {
            return base.Channel.solrqAsync(request);
        }
        
        public System.Threading.Tasks.Task<Glue.SolrRef.solrqResponse> solrqAsync(string q1, string q2) {
            Glue.SolrRef.solrqRequest inValue = new Glue.SolrRef.solrqRequest();
            inValue.q1 = q1;
            inValue.q2 = q2;
            return ((Glue.SolrRef.SolrTest)(this)).solrqAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Glue.SolrRef.NounVerbResponse Glue.SolrRef.SolrTest.NounVerb(Glue.SolrRef.NounVerbRequest request) {
            return base.Channel.NounVerb(request);
        }
        
        public string[] NounVerb(string query) {
            Glue.SolrRef.NounVerbRequest inValue = new Glue.SolrRef.NounVerbRequest();
            inValue.query = query;
            Glue.SolrRef.NounVerbResponse retVal = ((Glue.SolrRef.SolrTest)(this)).NounVerb(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Glue.SolrRef.NounVerbResponse> Glue.SolrRef.SolrTest.NounVerbAsync(Glue.SolrRef.NounVerbRequest request) {
            return base.Channel.NounVerbAsync(request);
        }
        
        public System.Threading.Tasks.Task<Glue.SolrRef.NounVerbResponse> NounVerbAsync(string query) {
            Glue.SolrRef.NounVerbRequest inValue = new Glue.SolrRef.NounVerbRequest();
            inValue.query = query;
            return ((Glue.SolrRef.SolrTest)(this)).NounVerbAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Glue.SolrRef.spellcheckResponse Glue.SolrRef.SolrTest.spellcheck(Glue.SolrRef.spellcheckRequest request) {
            return base.Channel.spellcheck(request);
        }
        
        public string spellcheck(string key) {
            Glue.SolrRef.spellcheckRequest inValue = new Glue.SolrRef.spellcheckRequest();
            inValue.key = key;
            Glue.SolrRef.spellcheckResponse retVal = ((Glue.SolrRef.SolrTest)(this)).spellcheck(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Glue.SolrRef.spellcheckResponse> Glue.SolrRef.SolrTest.spellcheckAsync(Glue.SolrRef.spellcheckRequest request) {
            return base.Channel.spellcheckAsync(request);
        }
        
        public System.Threading.Tasks.Task<Glue.SolrRef.spellcheckResponse> spellcheckAsync(string key) {
            Glue.SolrRef.spellcheckRequest inValue = new Glue.SolrRef.spellcheckRequest();
            inValue.key = key;
            return ((Glue.SolrRef.SolrTest)(this)).spellcheckAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Glue.SolrRef.QueryRetResponse Glue.SolrRef.SolrTest.QueryRet(Glue.SolrRef.QueryRetRequest request) {
            return base.Channel.QueryRet(request);
        }
        
        public string[] QueryRet(string key, string field) {
            Glue.SolrRef.QueryRetRequest inValue = new Glue.SolrRef.QueryRetRequest();
            inValue.key = key;
            inValue.field = field;
            Glue.SolrRef.QueryRetResponse retVal = ((Glue.SolrRef.SolrTest)(this)).QueryRet(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Glue.SolrRef.QueryRetResponse> Glue.SolrRef.SolrTest.QueryRetAsync(Glue.SolrRef.QueryRetRequest request) {
            return base.Channel.QueryRetAsync(request);
        }
        
        public System.Threading.Tasks.Task<Glue.SolrRef.QueryRetResponse> QueryRetAsync(string key, string field) {
            Glue.SolrRef.QueryRetRequest inValue = new Glue.SolrRef.QueryRetRequest();
            inValue.key = key;
            inValue.field = field;
            return ((Glue.SolrRef.SolrTest)(this)).QueryRetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Glue.SolrRef.AutoCompleteResponse Glue.SolrRef.SolrTest.AutoComplete(Glue.SolrRef.AutoCompleteRequest request) {
            return base.Channel.AutoComplete(request);
        }
        
        public string[] AutoComplete(string q, int limit) {
            Glue.SolrRef.AutoCompleteRequest inValue = new Glue.SolrRef.AutoCompleteRequest();
            inValue.q = q;
            inValue.limit = limit;
            Glue.SolrRef.AutoCompleteResponse retVal = ((Glue.SolrRef.SolrTest)(this)).AutoComplete(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Glue.SolrRef.AutoCompleteResponse> Glue.SolrRef.SolrTest.AutoCompleteAsync(Glue.SolrRef.AutoCompleteRequest request) {
            return base.Channel.AutoCompleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Glue.SolrRef.AutoCompleteResponse> AutoCompleteAsync(string q, int limit) {
            Glue.SolrRef.AutoCompleteRequest inValue = new Glue.SolrRef.AutoCompleteRequest();
            inValue.q = q;
            inValue.limit = limit;
            return ((Glue.SolrRef.SolrTest)(this)).AutoCompleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Glue.SolrRef.AutoSugResponse Glue.SolrRef.SolrTest.AutoSug(Glue.SolrRef.AutoSugRequest request) {
            return base.Channel.AutoSug(request);
        }
        
        public string[] AutoSug(string q) {
            Glue.SolrRef.AutoSugRequest inValue = new Glue.SolrRef.AutoSugRequest();
            inValue.q = q;
            Glue.SolrRef.AutoSugResponse retVal = ((Glue.SolrRef.SolrTest)(this)).AutoSug(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Glue.SolrRef.AutoSugResponse> Glue.SolrRef.SolrTest.AutoSugAsync(Glue.SolrRef.AutoSugRequest request) {
            return base.Channel.AutoSugAsync(request);
        }
        
        public System.Threading.Tasks.Task<Glue.SolrRef.AutoSugResponse> AutoSugAsync(string q) {
            Glue.SolrRef.AutoSugRequest inValue = new Glue.SolrRef.AutoSugRequest();
            inValue.q = q;
            return ((Glue.SolrRef.SolrTest)(this)).AutoSugAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Glue.SolrRef.splitterResponse Glue.SolrRef.SolrTest.splitter(Glue.SolrRef.splitterRequest request) {
            return base.Channel.splitter(request);
        }
        
        public string[] splitter(string info) {
            Glue.SolrRef.splitterRequest inValue = new Glue.SolrRef.splitterRequest();
            inValue.info = info;
            Glue.SolrRef.splitterResponse retVal = ((Glue.SolrRef.SolrTest)(this)).splitter(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Glue.SolrRef.splitterResponse> Glue.SolrRef.SolrTest.splitterAsync(Glue.SolrRef.splitterRequest request) {
            return base.Channel.splitterAsync(request);
        }
        
        public System.Threading.Tasks.Task<Glue.SolrRef.splitterResponse> splitterAsync(string info) {
            Glue.SolrRef.splitterRequest inValue = new Glue.SolrRef.splitterRequest();
            inValue.info = info;
            return ((Glue.SolrRef.SolrTest)(this)).splitterAsync(inValue);
        }
    }
}
