//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glue.CalculatorServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://calculator.bursteg.org/", ConfigurationName="CalculatorServiceReference.CalculatorService")]
    public interface CalculatorService {
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://calculator.bursteg.org/)
        [System.ServiceModel.OperationContractAttribute(Action="http://calculator.bursteg.org/CalculatorService/addRequest", ReplyAction="http://calculator.bursteg.org/CalculatorService/addResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Glue.CalculatorServiceReference.addResponse add(Glue.CalculatorServiceReference.addRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://calculator.bursteg.org/CalculatorService/addRequest", ReplyAction="http://calculator.bursteg.org/CalculatorService/addResponse")]
        System.Threading.Tasks.Task<Glue.CalculatorServiceReference.addResponse> addAsync(Glue.CalculatorServiceReference.addRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="add", WrapperNamespace="http://calculator.bursteg.org/", IsWrapped=true)]
    public partial class addRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int b;
        
        public addRequest() {
        }
        
        public addRequest(int a, int b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addResponse", WrapperNamespace="http://calculator.bursteg.org/", IsWrapped=true)]
    public partial class addResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public addResponse() {
        }
        
        public addResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculatorServiceChannel : Glue.CalculatorServiceReference.CalculatorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorServiceClient : System.ServiceModel.ClientBase<Glue.CalculatorServiceReference.CalculatorService>, Glue.CalculatorServiceReference.CalculatorService {
        
        public CalculatorServiceClient() {
        }
        
        public CalculatorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Glue.CalculatorServiceReference.addResponse Glue.CalculatorServiceReference.CalculatorService.add(Glue.CalculatorServiceReference.addRequest request) {
            return base.Channel.add(request);
        }
        
        public int add(int a, int b) {
            Glue.CalculatorServiceReference.addRequest inValue = new Glue.CalculatorServiceReference.addRequest();
            inValue.a = a;
            inValue.b = b;
            Glue.CalculatorServiceReference.addResponse retVal = ((Glue.CalculatorServiceReference.CalculatorService)(this)).add(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Glue.CalculatorServiceReference.addResponse> Glue.CalculatorServiceReference.CalculatorService.addAsync(Glue.CalculatorServiceReference.addRequest request) {
            return base.Channel.addAsync(request);
        }
        
        public System.Threading.Tasks.Task<Glue.CalculatorServiceReference.addResponse> addAsync(int a, int b) {
            Glue.CalculatorServiceReference.addRequest inValue = new Glue.CalculatorServiceReference.addRequest();
            inValue.a = a;
            inValue.b = b;
            return ((Glue.CalculatorServiceReference.CalculatorService)(this)).addAsync(inValue);
        }
    }
}
